### ISSUE TITLE
Burf bypassing strings

### ISSUE THREAD

**Issue by dan-silva** [kovisoft/paredit#15]
It looks like that the burf (for both directions) feature is not working when there are strings as elements of a expression:

Expected:
```
(aaa bbb ccc|)    --->    (aaa  bbb|)  ccc
(aaa "bbb" ccc|)    --->    (aaa  "bbb"|)  ccc
```
Current behavior:

```
(aaa bbb ccc|)    --->    (aaa  bbb|)  ccc
(aaa "bbb" ccc|)    --->    (aaa|) "bbb" ccc
```

... while it is slurping correctly on the given examples.

**Comment by kovisoft** [comment]
Fixed in commit https://github.com/kovisoft/paredit/commit/2a30789d0f699ba5b4fc0e7362f312aa143dd1f6

**Comment by dan-silva** [comment]
It's working now. Thank you!
