### ISSUE TITLE
Command for switching off paredit?

### ISSUE THREAD

**Issue by cwfoo** [kovisoft/paredit#26]
Is there a way to switch paredit on and off when editing a file? e.g. Something similar to `:PareditOn`, `:PareditOff`, `:PareditToggle`.

**Comment by kovisoft** [comment]
I'm on vacation this week and I'm away from my computer, but I try to give you a quick answer. Do you need a keyboard mapping for switching paredit on and off? In this case it's `<Leader>(` (by default `,(`).

**Comment by cwfoo** [comment]
@kovisoft Your suggestion did not work. I figured it out: `:let g:paredit_mode=0` switches off paredit, and `:let g:paredit_mode=1` switches it on again.

Will you consider adding `:PareditOn`, `:PareditOff`, and `:PareditToggle` for convenience?

**Comment by kovisoft** [comment]
Ah, I think you use paredit.vim without slimv.vim, right? All these keybindings are defined in slimv.vim. That's because originally paredit.vim was part of slimv. I see the problem now, I'll add the same mappings when paredit is used without slimv.

**Comment by kovisoft** [comment]
Added mapping `,(` for `PareditToggle()` when Paredit is used without Slimv. See commit https://github.com/kovisoft/paredit/commit/c41ce8cd8852dadf6b88aa823c28db91192b0f9f
