### ISSUE TITLE
Vimdiff 'dp' and 'do' keybindings broken

### ISSUE THREAD

**Issue by cwfoo** [kovisoft/paredit#27]
Paredit interferes with the `dp` and `do` keybindings in Vimdiff. Contrary to expectations, nothing observable happens when `dp` and `do` are used in Vimdiff when Paredit is enabled.

**Comment by kovisoft** [comment]
Fixed in commit https://github.com/kovisoft/paredit/commit/a62c77f81ac38c72bb0c77c51a637739b89ee9ff
