### ISSUE TITLE
Motions [[, ]], ( and ) are not populating the jumplist

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovisoft/paredit#29]
Motions `[[`, `]]`, `(` and `)` are not populating the jumplist.

In a non-paredit mode, these 4 motion commands populate the jumplist and allow the user to press `CTRL-O` and go back to the previous position.
This is a default behavior of vim.

**Comment by kovisoft** [comment]
Fixed in commit https://github.com/kovisoft/paredit/commit/81e3a7db233110d37ecea8345d0fd5431e2c2f37

**Comment by mihaicristiantanase** [comment]
Tested and works perfectly.
Thank you!
