### ISSUE TITLE
Link to Cheat Sheet Gone

### ISSUE THREAD

**Issue by mkohlhaas** [kovisoft/paredit#31]
The reference to the cheat sheet is gone and really not necessary as the docs are more than suffficient:

https://github.com/kovisoft/paredit/blob/d99905abe084014352f6c3e9be1a3f5f0d1ebbb8/doc/paredit.txt#L371

**Comment by kovisoft** [comment]
Thank you for pointing this out. It looks like Davide removed his repositories from GitHub, and I can't find his cheat sheet anywhere. All I can do is remove the reference from the doc.

**Comment by mkohlhaas** [comment]
Yes, I searched the internet, too. It's gone. But we don't need it. Your doc is more than enough.

**Comment by kovisoft** [comment]
I have removed the orphaned reference, see commit https://github.com/kovisoft/paredit/commit/eb9a113f571f2d1492463c53765fc4d0dc225768
Thanks for the feedback.
