### ISSUE TITLE
Paredit interferes with pasting when disabled

### ISSUE THREAD

**Issue by NieDzejkob** [kovisoft/paredit#34]
Steps to reproduce:
1. `vim test.scm`
2. `:call PareditToggle()` to disable paredit
3. `i(abc<ESC>`
4. `yyp`

Expected result:
```
(abc
(abc
```

Actual result:
```
(abc
 abc
```

**Comment by kovisoft** [comment]
Thanks for the feedback. Fixed in commit https://github.com/kovisoft/paredit/commit/14ff56829d068d56ad9cef7b145d66539ef422d3

**Comment by NieDzejkob** [comment]
Indeed, I can confirm that this is fixed in the new version.
