### ISSUE TITLE
Commenting out an s-exp breaks paredit

### ISSUE THREAD

**Issue by NieDzejkob** [kovisoft/paredit#35]
```
(abc
  #;(def (ghi
    (jkl)))
  (mno (pqr)))
```

Consider this code in a scheme file. `2Gdj` results in

```
(abc
  ))
  (mno (pqr)))
```

while I would expect

```
(abc
  (mno (pqr)))
```

**Comment by kovisoft** [comment]
Thanks for the feedback. I also found a similar problem with unbalanced s-expressions in multi-line comments:

```
(abc
  #|(def (ghi
    (jkl|#
  (mno (pqr)))
```

Both fixed in commit https://github.com/kovisoft/paredit/commit/6941b5d04483c93b2a03a54435054e5974f06b38
