### ISSUE TITLE
Incorrect splicing in a Common Lisp #'(lambda (...) ...)

### ISSUE THREAD

**Issue by cwfoo** [kovisoft/paredit#38]
1. 
    ```
    #'(lambda (x) (+ x 1))
    ```

    If I position the cursor on the opening bracket of `(+ x 1)` and press `<Leader>S` (splice):
    * Observed result: nothing happens
    * Expected result: `#'(lambda (x) + x 1)`

2.
    ```
    (f #'(lambda (x) (+ x 1)))
    ```
    If I position the cursor on the opening bracket of `(+ x 1)` and press `<Leader>S` (splice):
    * Observed result: `f #'(lambda (x) (+ x 1))`
    * Expected result: `(f #'(lambda (x) + x 1))`

3.
    ```
    (g (f #'(lambda (x) (+ x 1))))
    ```
    If I position the cursor on the opening bracket of `(+ x 1)` and press `<Leader>S` (splice):
    * Observed result: `(g f #'(lambda (x) (+ x 1)))`
    * Expected result: `(g (f #'(lambda (x) + x 1)))`

**Comment by kovisoft** [comment]
Thank you for the bug report. Fixed in commit https://github.com/kovisoft/paredit/commit/76c1fb8f8dedccefe8df4bffa099af3d19e25a98

**Comment by cwfoo** [comment]
Thank you for the fix.
