### ISSUE TITLE
Attempting to slurp a string on the last line barfs instead

### ISSUE THREAD

**Issue by cwfoo** [kovisoft/paredit#40]
To reproduce:

1. Open a Scheme file (`myprogram.scm`), and insert the following on the last line:
    ```scheme
    (define s) "hello"
    ```
2. Position the cursor on the closing parenthesis, and try to slurp the string (`<Leader>>`).
3. Observation: paredit barfs the identifier instead.
    ```scheme
    (define) s "hello"
    ```

This behavior only seems to occur when the string is the very last item on the last line of the buffer

**Comment by kovisoft** [comment]
First I was unable to reproduce the problem, but then I realized that this probably depends on the `virtualedit` option. Fixed in commit https://github.com/kovisoft/paredit/commit/38231a6f299b8b23563ba0fd471291cb040f0c20

**Comment by cwfoo** [comment]
Thank you for fixing the problem.
