### ISSUE TITLE
Slurping a multibyte character on the last column destroys the character

### ISSUE THREAD

**Issue by cwfoo** [kovisoft/paredit#41]
If a multibyte character is on the last column of a line, slurping it would destroy it.

Steps to reproduce:

1. Open a Scheme file, and insert this:
    ```scheme
    (f) λ
    ```
2. Position the cursor on the closing parenthesis, and slurp the lambda (`<Leader>>`).
3. Result:
    
    ![2021-03-08_00-54](https://user-images.githubusercontent.com/11555232/110247786-e51c4300-7fa8-11eb-84dd-ae387a9deb11.png)

**Comment by kovisoft** [comment]
Seems to be caused by the same issue with `virtualedit` as the previous one. Fixed in commit https://github.com/kovisoft/paredit/commit/38231a6f299b8b23563ba0fd471291cb040f0c20

**Comment by cwfoo** [comment]
Thank you for fixing this.

> Seems to be caused by the same issue with `virtualedit` as the previous one. Fixed in commit [38231a6](https://github.com/kovisoft/paredit/commit/38231a6f299b8b23563ba0fd471291cb040f0c20)

For future reference: "previous one" refers to #40.
