### ISSUE TITLE
Splice does not work for forms not encased with parens

### ISSUE THREAD

**Issue by stelcodes** [kovisoft/paredit#43]
Hi there, I've noticed that paredit doesn't splice in my EDN (Clojure) files when there isn't a pair of parens somewhere around the form I'm trying to splice. This might affect other commands but I've just noticed splicing. The workaround is to wrap with parens before splicing. The parens don't have to be directly around the form: even a paren wrapping 10 levels up will enable splicing. I tried to take a look at the code but I can't tease out where the issue may lie or if this is maybe a fundamental incompatibility with Paredit's system.

Minimal Reproduction:
`example.edn`:
```clojure
{:test ["test"]}
```
- try to splice the `["test"]` vector away

Parens are very uncommon in EDN so I usually just wrap the top form in parens whenever I want to edit it as a workaround.

Paredit: 97d51d099523b37bb35cbcf3564cbfb46e66e4ec April 5 2021
Neovim: v0.7.0

**Comment by kovisoft** [comment]
Thank you for the feedback! I confirm that this is a bug in paredit. I'll let you know when I have a fix for that.

**Comment by kovisoft** [comment]
Fixed in commit https://github.com/kovisoft/paredit/commit/c90dc16ada33322f8efc9435f6cae5711f4477d4

**Comment by stelcodes** [comment]
Awesome thank you!
